PARTS = {
  // Components
  'carite sheet':         {'iron': 50},
  'microdensity fabric':  {'iron': 50, 'platinum': 10},
  'suspension fluid':     {'carbon': 50},
  'electron vapor':       {'suspension fluid': 1, 'plutonium': 1000},
  'antimatter':           {'electron vapor': 1, 'heridium': 50, 'zinc': 20},
  // Oxides
  'iron':         {},
  'zinc':         {},
  'titanium':     {},
  // Silicates
  'heridium':     {},
  'platinum':     {},
  'chrysonite':   {},
  // Isotopes
  'carbon':       {},
  'thamium9':     {},
  'plutonium':    {},
  // Neutral
  'nickel':       {},
  'iridium':      {},
  'copper':       {},
  'gold':         {},
  'aluminium':    {},
  'emeril':       {},
  'candensium':   {},
  'fervidium':    {},
  'mordite':      {},
  'pugneum':      {},
  'spadonium':    {},
  'tropheum':     {},
  'temerium':     {},
  'coryzagen':    {},
  'coprite':      {},
  // Exotic
  'antrium':      {},
  'rigogen':      {},
  'rubeum':       {},
  'viridium':     {},
  'omegon':       {},
  'radnox':       {},
  'murrine':      {},
  'calium':       {},
  'cymatygen':    {},
};
